version: '3'

services:
  mongo:
    image: 'mongo'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_persistant:/data/db
      - ./core/database-scripts/mongo-js:/docker-entrypoint-initdb.d

volumes:
  mongo_persistant: {}